'use client'

import Link from 'next/link'
import { ArrowRight, Check, ChevronRight, LockKeyhole, Music2, Sparkles, Upload, Users } from 'lucide-react'

const dimensions = [
  ['Curiosity', 82], ['Adventure', 91], ['Culture', 88], ['Productivity', 64],
  ['Activity', 71], ['Social', 76], ['Finance', 58], ['Balance', 61],
]

export default function LandingPage() {
  return <main className="landing-page">
    <nav className="landing-nav"><Link href="/" className="brand"><span className="brand-mark">R</span><span>Rate My Life</span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#privacy">Privacy</a><Link href="/sign-in">Log in</Link><Link href="/sign-up" className="nav-cta">Get started <ArrowRight size={15} /></Link></div></nav>
    <section className="landing-hero"><div className="hero-copy"><span className="landing-eyebrow"><Sparkles size={14} /> YOUR DIGITAL LIFE, DECIPHERED</span><h1>What does your life actually <em>say about you?</em></h1><p>Connect the parts of your digital life you choose to share. We&apos;ll turn them into insights, patterns, and a Life Score.</p><div className="hero-actions"><Link href="/sign-up" className="primary-button">Rate My Life <ArrowRight size={17} /></Link><a href="#example" className="secondary-button">See an example <ChevronRight size={16} /></a></div><div className="trust-row"><LockKeyhole size={15} /> Private by default <span /> No judgment, just patterns</div></div><div className="demo-wrap" id="example"><div className="demo-score-card"><div className="demo-card-top"><span>YOUR LIFE SCORE</span><span className="demo-period">SEPTEMBER 2026</span></div><div className="demo-score"><strong>74</strong><span>/ 100</span></div><div className="demo-bars">{dimensions.map(([label, score]) => <div className="demo-bar" key={label}><span>{label}</span><div><i style={{ width: `${score}%` }} /></div><b>{score}</b></div>)}</div></div><div className="demo-insight"><span>THE WEEKEND EXPLORER</span><p>&quot;Your passport gets more exercise than your gym membership.&quot;</p><div><Sparkles size={15} /> A pattern worth noticing</div></div></div></section>
    <section className="landing-proof"><span>YOUR LIFE HAS A PATTERN</span><strong>Not a productivity score.<br /><em>A more interesting mirror.</em></strong><p>Rate My Life brings the tiny signals of your everyday life together, so you can notice what no single app can show you.</p></section>
    <section className="how-section" id="how-it-works"><div className="section-intro"><span className="landing-eyebrow">HOW IT WORKS</span><h2>Four steps to a<br /><em>better read on you.</em></h2></div><div className="steps-grid">{[['01','Connect your data','Choose the sources that feel right — music, calendar, screenshots and more.',Music2],['02','We find the signal','We analyze patterns, not private content, and keep the logic understandable.',Sparkles],['03','Get your Life Report','See your score, dimensions, surprising stats and a story that sounds like you.',Check],['04','Compare with friends','Share the parts you want and discover where your lives overlap.',Users]].map(([number,title,copy,Icon]) => <div className="step-card" key={number as string}><span className="step-number">{number}</span><div className="step-icon"><Icon size={20} /></div><h3>{title as string}</h3><p>{copy as string}</p></div>)}</div></section>
    <section className="privacy-section" id="privacy"><div className="privacy-art"><div className="privacy-orb"><LockKeyhole size={40} /></div><span className="privacy-chip chip-one">You choose</span><span className="privacy-chip chip-two">Delete anytime</span><span className="privacy-chip chip-three">No secret tracking</span></div><div><span className="landing-eyebrow">YOUR DATA, YOUR RULES</span><h2>You choose<br /><em>what to share.</em></h2><p>We only analyze the data sources you explicitly connect or upload. No silent collection, no selling your story, and no sensitive inferences about who you are.</p><ul><li><Check size={16} /> Disconnect or delete anything, anytime</li><li><Check size={16} /> Metadata first — content stays yours</li><li><Check size={16} /> Clear explanations for every insight</li></ul><Link href="/sign-up" className="primary-button">Discover your life <ArrowRight size={17} /></Link></div></section>
    <footer className="landing-footer"><div className="brand"><span className="brand-mark">R</span><span>Rate My Life</span></div><span>Made for the curious.</span><div><Link href="/sign-in">Log in</Link><Link href="/sign-up">Get started</Link></div></footer>
  </main>
}
